spring.application.name=uav-unified-api
server.port=8081

# ==== DATOS DE RAILWAY (USANDO DATABASE_PUBLIC_URL) ====
# De: postgresql://postgres:TU_PASSWORD@shinkansen.proxy.rlwy.net:21388/railway

spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:21388/railway
spring.datasource.username=postgres
spring.datasource.password=DlTFMilixrVWiZlueRGniZwcfFWWTtmy

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
